import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Pause, Play, RefreshCw } from "lucide-react";
import { useSchedule, useScheduleAction } from "../../hooks/useOperations";
import { Button, Card, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge, useToast } from "../../components/ui";
import { errorMessage } from "../../lib/api";
import { formatDate, titleCase } from "../../lib/utils";

export function AgentTemplateDetailPage() {
  const { id } = useParams(); const schedule = useSchedule(id); const action = useScheduleAction(id); const toast = useToast();
  if (schedule.isLoading) return <LoadingState label="Loading schedule" />;
  if (schedule.error || !schedule.data) return <ErrorState message={errorMessage(schedule.error)} />;
  const item=schedule.data;
  async function run(kind:"run"|"pause"|"resume") { try { await action.mutateAsync(kind); toast.push({kind:"success",title:`Schedule ${kind} complete`,message:"The recurring payroll schedule was updated."}); } catch(e){toast.push({kind:"error",title:"Schedule action failed",message:errorMessage(e)});} }
  return <div className="dashboard-shell agent-page"><Link className="template-detail-back-link" to="/agent"><ArrowLeft size={14}/><span>Back</span></Link><PageHeader eyebrow="Payroll schedule" title={item.name} accentTitle={titleCase(item.frequency)} description="Fresh private payroll shells, never copied salary rows." actions={<div className="row"><Button variant="secondary" onClick={()=>run("run")} disabled={action.isPending}><RefreshCw size={15}/>Run now</Button>{item.active?<Button variant="secondary" onClick={()=>run("pause")} disabled={action.isPending}><Pause size={15}/>Pause</Button>:<Button onClick={()=>run("resume")} disabled={action.isPending}><Play size={15}/>Resume</Button>}</div>} /><div className="stats-row"><div className="stat-card"><div className="stat-value"><StatusBadge value={item.active?"active":"paused"}/></div><div className="stat-label">Status</div></div><div className="stat-card"><div className="stat-value">{item.run_count}</div><div className="stat-label">Runs created</div></div><div className="stat-card"><div className="stat-value">{item.timezone_name}</div><div className="stat-label">Timezone</div></div></div><Card title="Schedule details"><div className="key-grid"><span>Next run</span><strong>{formatDate(item.next_run_at)}</strong><span>Funding window</span><strong>{item.funding_window_hours} hours</strong><span>Withdrawal window</span><strong>{item.minimum_withdrawal_window_seconds} seconds</strong><span>Last run</span><strong>{item.last_run_at?formatDate(item.last_run_at):"Not run"}</strong></div></Card><Card title="Executions" subtitle="Fresh payroll shells created by this schedule.">{item.executions?.length?<div className="table-wrap"><table><thead><tr><th>Scheduled for</th><th>Payroll</th><th>Status</th><th>Message</th></tr></thead><tbody>{item.executions.map((execution)=><tr key={execution.id}><td>{formatDate(execution.scheduled_for)}</td><td>{execution.payroll_run||"-"}</td><td><StatusBadge value={execution.status}/></td><td>{execution.message||"-"}</td></tr>)}</tbody></table></div>:<EmptyState title="No executions" description="The first run will appear here."/>}</Card></div>;
}
